name: Build docker image

on:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  USE_BAZEL_VERSION: "7.2.1"

jobs:
  build_docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: install python dependencies
      run: |
        pip install pip --upgrade --quiet
        pip install wheel setuptools pipdeptree --upgrade --quiet

    - name: Build docker
      run: |
        export BUILD_ID="$(date +%s)-$(LC_ALL=C tr -dc a-z0-9 </dev/urandom | head -c 10)"
        export DOCKER_IMAGE="gcr.io/tfx-oss-public/tfx_smoke_test:${BUILD_ID}"
        DOCKER_IMAGE_REPO="gcr.io/tfx-testing/ai-platform-pipelines-e2e-test" \
        DOCKER_IMAGE_TAG="$(date +%s)-$(LC_ALL=C tr -dc a-z0-9 </dev/urandom | head -c 10)" \
        tfx/tools/docker/build_docker_image.sh
        docker inspect ${DOCKER_IMAGE}
